import {
	HelpCircle,
	Home,
	User,
	Settings,
	Book,
	Heart,
	Star,
	Music,
	Camera,
	Map,
	Mail,
	Phone,
	Calendar,
	Tag,
	Folder,
	File,
	Image,
	Video,
	Download,
	Upload,
	Search,
	Bell,
	Lock,
	Unlock,
	Shield,
	AlertCircle,
	CheckCircle,
	XCircle,
	Info,
	ChevronRight,
	ChevronLeft,
	ArrowRight,
	ArrowLeft,
	PlusCircle,
	MinusCircle,
	Edit,
	Trash,
	Save,
	Share,
	Gift,
	ShoppingCart,
	CreditCard,
	Banknote,
	Wallet,
	TrendingUp,
	TrendingDown,
	BarChart,
	PieChart,
	LineChart,
	Target,
	Award,
	Trophy,
	Zap,
	Battery,
	Wifi,
	Bluetooth,
	Monitor,
	Laptop,
	Smartphone,
	Tablet,
	Headphones,
	Speaker,
	Gamepad2,
	Dice6,
	Puzzle,
	Palette,
	Brush,
	Pen,
	Pencil,
	Eraser,
	Scissors,
	Ruler,
	Compass,
	Globe,
	Navigation,
	Plane,
	Car,
	Bike,
	Train,
	Ship,
	Bus,
	Fuel,
	ParkingCircle,
	Building,
	Store,
	Briefcase,
	Building2,
	Hotel,
	School,
	GraduationCap,
	Library,
	Microscope,
	FlaskConical,
	Calculator,
	Code,
	Terminal,
	Cpu,
	Database,
	Server,
	Cloud,
	CloudRain,
	CloudSnow,
	Sun,
	Moon,
	Umbrella,
	Thermometer,
	Wind,
	Droplet,
	Flame,
	TreePine,
	Leaf,
	Flower,
	Apple,
	Coffee,
	UtensilsCrossed,
	IceCream,
	Cake,
	Cookie,
	Croissant,
	Fish,
	Beef,
	Wheat,
	Egg,
	Milk,
	Beer,
	Wine,
	ChefHat,
	Shirt,
	Footprints,
	Watch,
	Glasses,
	Key,
	Package,
	Box,
	Archive,
	Snowflake,
	Rainbow,
	Mountain,
	Waves,
	Sunrise,
	Sunset,
	Hand,
	Handshake,
	Lightbulb,
	Smile,
	Users,
	UserPlus,
	MessageSquare,
	ThumbsUp,
	ThumbsDown,
	AlertTriangle,
	Frown,
	MoreHorizontal,
	ArrowRightLeft,
	Flag,
	Film,
	Sparkles,
} from 'lucide-react';

// Фиксированный список популярных иконок
export const iconList = [
	// Основные
	{ name: 'HomeIcon', component: Home },
	{ name: 'UserIcon', component: User },
	{ name: 'SettingsIcon', component: Settings },
	{ name: 'BookIcon', component: Book },
	{ name: 'HeartIcon', component: Heart },
	{ name: 'StarIcon', component: Star },
	{ name: 'MusicIcon', component: Music },
	{ name: 'CameraIcon', component: Camera },
	{ name: 'MapIcon', component: Map },
	{ name: 'MailIcon', component: Mail },
	{ name: 'PhoneIcon', component: Phone },
	{ name: 'CalendarIcon', component: Calendar },
	{ name: 'TagIcon', component: Tag },
	{ name: 'FolderIcon', component: Folder },
	{ name: 'FileIcon', component: File },
	{ name: 'ImageIcon', component: Image },
	{ name: 'VideoIcon', component: Video },
	{ name: 'DownloadIcon', component: Download },
	{ name: 'UploadIcon', component: Upload },
	{ name: 'SearchIcon', component: Search },
	{ name: 'BellIcon', component: Bell },
	{ name: 'LockIcon', component: Lock },
	{ name: 'UnlockIcon', component: Unlock },
	{ name: 'ShieldIcon', component: Shield },
	{ name: 'AlertCircleIcon', component: AlertCircle },
	{ name: 'CheckCircleIcon', component: CheckCircle },
	{ name: 'XCircleIcon', component: XCircle },
	{ name: 'InfoIcon', component: Info },
	{ name: 'ChevronRightIcon', component: ChevronRight },
	{ name: 'ChevronLeftIcon', component: ChevronLeft },
	{ name: 'ArrowRightIcon', component: ArrowRight },
	{ name: 'ArrowLeftIcon', component: ArrowLeft },
	{ name: 'PlusCircleIcon', component: PlusCircle },
	{ name: 'MinusCircleIcon', component: MinusCircle },
	{ name: 'EditIcon', component: Edit },
	{ name: 'TrashIcon', component: Trash },
	{ name: 'SaveIcon', component: Save },
	{ name: 'ShareIcon', component: Share },
	{ name: 'HelpCircleIcon', component: HelpCircle },
	{ name: 'HandIcon', component: Hand },
	{ name: 'HandshakeIcon', component: Handshake },
	{ name: 'LightbulbIcon', component: Lightbulb },
	{ name: 'SmileIcon', component: Smile },
	{ name: 'WavesIcon', component: Waves },
	{ name: 'UsersIcon', component: Users },
	{ name: 'UserPlusIcon', component: UserPlus },
	{ name: 'MessageSquareIcon', component: MessageSquare },
	{ name: 'ThumbsUpIcon', component: ThumbsUp },
	{ name: 'ThumbsDownIcon', component: ThumbsDown },
	{ name: 'AlertTriangleIcon', component: AlertTriangle },
	{ name: 'FrownIcon', component: Frown },
	{ name: 'MoreHorizontalIcon', component: MoreHorizontal },
	{ name: 'ArrowRightLeftIcon', component: ArrowRightLeft },
	{ name: 'FlagIcon', component: Flag },
	{ name: 'FilmIcon', component: Film },
	{ name: 'SparklesIcon', component: Sparkles },
	// Финансы и коммерция
	{ name: 'GiftIcon', component: Gift },
	{ name: 'ShoppingCartIcon', component: ShoppingCart },
	{ name: 'CreditCardIcon', component: CreditCard },
	{ name: 'BanknoteIcon', component: Banknote },
	{ name: 'WalletIcon', component: Wallet },
	{ name: 'TrendingUpIcon', component: TrendingUp },
	{ name: 'TrendingDownIcon', component: TrendingDown },
	{ name: 'BarChartIcon', component: BarChart },
	{ name: 'PieChartIcon', component: PieChart },
	{ name: 'LineChartIcon', component: LineChart },
	{ name: 'TargetIcon', component: Target },
	{ name: 'AwardIcon', component: Award },
	{ name: 'TrophyIcon', component: Trophy },
	// Технологии
	{ name: 'ZapIcon', component: Zap },
	{ name: 'BatteryIcon', component: Battery },
	{ name: 'WifiIcon', component: Wifi },
	{ name: 'BluetoothIcon', component: Bluetooth },
	{ name: 'MonitorIcon', component: Monitor },
	{ name: 'LaptopIcon', component: Laptop },
	{ name: 'SmartphoneIcon', component: Smartphone },
	{ name: 'TabletIcon', component: Tablet },
	{ name: 'HeadphonesIcon', component: Headphones },
	{ name: 'SpeakerIcon', component: Speaker },
	{ name: 'Gamepad2Icon', component: Gamepad2 },
	{ name: 'Dice6Icon', component: Dice6 },
	{ name: 'PuzzleIcon', component: Puzzle },
	{ name: 'CodeIcon', component: Code },
	{ name: 'TerminalIcon', component: Terminal },
	{ name: 'CpuIcon', component: Cpu },
	{ name: 'DatabaseIcon', component: Database },
	{ name: 'ServerIcon', component: Server },
	{ name: 'CloudIcon', component: Cloud },
	// Творчество
	{ name: 'PaletteIcon', component: Palette },
	{ name: 'BrushIcon', component: Brush },
	{ name: 'PenIcon', component: Pen },
	{ name: 'PencilIcon', component: Pencil },
	{ name: 'EraserIcon', component: Eraser },
	{ name: 'ScissorsIcon', component: Scissors },
	{ name: 'RulerIcon', component: Ruler },
	{ name: 'CompassIcon', component: Compass },
	// Навигация и транспорт
	{ name: 'GlobeIcon', component: Globe },
	{ name: 'NavigationIcon', component: Navigation },
	{ name: 'PlaneIcon', component: Plane },
	{ name: 'CarIcon', component: Car },
	{ name: 'BikeIcon', component: Bike },
	{ name: 'TrainIcon', component: Train },
	{ name: 'ShipIcon', component: Ship },
	{ name: 'BusIcon', component: Bus },
	{ name: 'FuelIcon', component: Fuel },
	{ name: 'ParkingCircleIcon', component: ParkingCircle },
	// Здания и места
	{ name: 'BuildingIcon', component: Building },
	{ name: 'StoreIcon', component: Store },
	{ name: 'BriefcaseIcon', component: Briefcase },
	{ name: 'Building2Icon', component: Building2 },
	{ name: 'HotelIcon', component: Hotel },
	{ name: 'SchoolIcon', component: School },
	{ name: 'GraduationCapIcon', component: GraduationCap },
	{ name: 'LibraryIcon', component: Library },
	{ name: 'MicroscopeIcon', component: Microscope },
	{ name: 'FlaskConicalIcon', component: FlaskConical },
	{ name: 'CalculatorIcon', component: Calculator },
	// Еда и напитки
	{ name: 'AppleIcon', component: Apple },
	{ name: 'CoffeeIcon', component: Coffee },
	{ name: 'UtensilsCrossedIcon', component: UtensilsCrossed },
	{ name: 'IceCreamIcon', component: IceCream },
	{ name: 'CakeIcon', component: Cake },
	{ name: 'CookieIcon', component: Cookie },
	{ name: 'CroissantIcon', component: Croissant },
	{ name: 'FishIcon', component: Fish },
	{ name: 'BeefIcon', component: Beef },
	{ name: 'WheatIcon', component: Wheat },
	{ name: 'EggIcon', component: Egg },
	{ name: 'MilkIcon', component: Milk },
	{ name: 'BeerIcon', component: Beer },
	{ name: 'WineIcon', component: Wine },
	{ name: 'ChefHatIcon', component: ChefHat },
	// Одежда и аксессуары
	{ name: 'ShirtIcon', component: Shirt },
	{ name: 'FootprintsIcon', component: Footprints },
	{ name: 'WatchIcon', component: Watch },
	{ name: 'GlassesIcon', component: Glasses },
	// Погода и природа
	{ name: 'CloudRainIcon', component: CloudRain },
	{ name: 'CloudSnowIcon', component: CloudSnow },
	{ name: 'SunIcon', component: Sun },
	{ name: 'UmbrellaIcon', component: Umbrella },
	{ name: 'ThermometerIcon', component: Thermometer },
	{ name: 'WindIcon', component: Wind },
	{ name: 'DropletIcon', component: Droplet },
	{ name: 'FlameIcon', component: Flame },
	{ name: 'TreePineIcon', component: TreePine },
	{ name: 'LeafIcon', component: Leaf },
	{ name: 'FlowerIcon', component: Flower },
	{ name: 'SnowflakeIcon', component: Snowflake },
	{ name: 'RainbowIcon', component: Rainbow },
	{ name: 'MountainIcon', component: Mountain },
	{ name: 'WavesIcon', component: Waves },
	{ name: 'SunriseIcon', component: Sunrise },
	{ name: 'SunsetIcon', component: Sunset },
	{ name: 'MoonIcon', component: Moon },
	// Другие
	{ name: 'KeyIcon', component: Key },
	{ name: 'PackageIcon', component: Package },
	{ name: 'BoxIcon', component: Box },
	{ name: 'ArchiveIcon', component: Archive },
];
